In [1]:
import numpy as np
import os
from sklearn.cluster import KMeans
import csv
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn import svm

In [2]:
def remnpy(filename):
	for i in range(len(filename)):
		if(filename[i:i+4]==".npy"):
			return filename[:i]
	return ""

In [13]:
files = os.listdir("train")
inp = np.array([])
inp = np.reshape(inp, [-1, 784])
inp_tag = []
inp_dict = {}
ite = 0
for file in files:
    inp = np.concatenate((inp, np.load("train/" + file)), axis = 0)
    inp_dict[ite] = remnpy(file)
    for i in range(0, 5000):
    	inp_tag.append(ite)
    ite += 1
inp_tag = np.array(inp_tag)

In [14]:
inp = StandardScaler().fit_transform(inp)

In [15]:
pca = PCA(n_components=10)
inputs_pca = pca.fit_transform(inp)

In [16]:
test_inp = np.load("test/test.npy")
test_inp = StandardScaler().fit_transform(test_inp)
outputs_pca = pca.transform(test_inp)

c:\users\prakhar ganesh\appdata\local\programs\python\python36\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [17]:
svm_model = svm.LinearSVC(C=1)
svm_model.fit(inputs_pca, inp_tag)
all_outs = svm_model.predict(outputs_pca)

In [18]:
myFile = open('pca.csv', 'w', newline='')
with myFile:
    fieldnames = ['ID', 'CATEGORY']
    writer = csv.DictWriter(myFile, fieldnames=fieldnames)
    writer.writeheader()
    for i, ele in enumerate(all_outs):
        writer.writerow({'ID' : str(i), 'CATEGORY' : inp_dict[ele]})

inp_acc = svm_model.predict(inputs_pca)

count = 0
total = 0
for ele, real in zip(inp_acc, inp_tag):
    if(ele==real):
        count += 1
    total += 1

print(count)
print(total)
print((count + 0.0)/total)

47950
100000
0.4795


In [6]:
import numpy as np

In [16]:
a = np.random.rand(3, 4)

In [17]:
print(a)
a = np.reshape(a, (-1, 2, 2))
print(a)

[[0.2211391  0.65583029 0.08870877 0.20244401]
 [0.07090061 0.23360283 0.98931129 0.10196051]
 [0.2306974  0.30078853 0.87030007 0.97697851]]
[[[0.2211391  0.65583029]
  [0.08870877 0.20244401]]

 [[0.07090061 0.23360283]
  [0.98931129 0.10196051]]

 [[0.2306974  0.30078853]
  [0.87030007 0.97697851]]]
